server:
    port: 1001

spring:
    datasource:
        password: 123456
        username: root
        url: jdbc:mysql://localhost:3306/mydb

    jpa:
        hibernate:
            ddl-auto: update
